### ISSUE TITLE
WRMEM used User mode instead of Kernel mode

### ISSUE THREAD

**Issue by rkopka42** [kaiwan/device-memory-readwrite#5]
First: I use the tool to access the PINMUX control registers on a TI AM335x ARM Cortex-A8. These are protected, so that you need the Kernel Mode for writes.

I define an iobase with
insmod devmem_rw.ko iobase_start=0x44E10000 iobase_len=0x100

./wrmem -o 860 27  (e.g.) didn't work (... user mode)

At line 98 I added the first "if", like it is used in RDMEM:
if (st_wrm.flag != USE_IOBASE) {
        if (is_user_address(st_wrm.addr)) {
            if (uaddr_valid(st_wrm.addr) == -1) {
                fprintf(stderr,
                    "%s: the (usermode virtual) address passed (%p) seems to be invalid. Aborting...\n",
                    argv[0], (void *)st_wrm.addr);
                close(fd);
                exit(1);
            }
        }
}

I didn't analyse the code in depth, as this worked right away. So I don't know if this is a good solution.

**Comment by kaiwan** [comment]
Thanks; let me check..

**Comment by kaiwan** [comment]
Thanks @rkopka42 ; I've incorporated your line...
As well, this pushed me to do several pending cleanups, a better Makefile, etc.
Thanks :-) 
Will close this ...
